name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# This makes sure to only run one instance of this workflow per individual PR and pushes.
# We need this especially for the release step, because it has side effects.
# But it's also good in general, there's no need to finish action runs for commits
# when you push another one right after.
# Assumption: We push less frequently than it takes for this workflow to finish
concurrency:
  # For a push to the main branch, github.ref is refs/heads/<branch_name>
  # For a pull request, github.ref is refs/pull/<pr_number>/merge
  group: ${{ github.ref }}
  # We don't want to cancel in progress workflows for pushes to the main branch,
  # because it could be in the process of doing a release.
  # Better wait until it's done
  cancel-in-progress: ${{ github.event_name != 'pull' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: build
        run: nix-build -A ci

      - name: release
        if: ${{ github.event_name == 'push' }}
        run: scripts/release.sh
        env:
          GH_TOKEN: ${{ github.token }}

  test-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: test update script
        run: |
          nix-build -A autoPrUpdate
          {
            result/bin/auto-pr-update .
            echo ""
            echo '```diff'
            git diff
            echo '```'
          } > $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ github.token }}
