name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: build
        run: nix-build -A ci

  test-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: test update script
        run: |
          nix-build -A autoPrUpdate
          {
            result/bin/auto-pr-update .
            echo ""
            echo '```diff'
            git diff
            echo '```'
          } > $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ github.token }}
