name: Update Nixpkgs pin
on:
  workflow_dispatch: # Allows triggering manually
  schedule:
    - cron: '47 14 * * *' # runs every day at 14:47 UTC (chosen somewhat randomly)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        path: repo

      - uses: cachix/install-nix-action@v26

      - name: update
        run: |
          nix-build repo -A autoPrUpdate
          result/bin/auto-pr-update > body

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # To trigger CI for automated PRs, we use a separate machine account
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
          # and https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork
          token: ${{ secrets.MACHINE_USER_PAT }}
          push-to-fork: infinixbot/nixpkgs-check-by-name
          committer: infinixbot <infinixbot@infinisil.com>
          author: infinixbot <infinixbot@infinisil.com>
          commit-message: "Automated update"
          branch: auto-update
          title: "Automated update"
          body-path: body
